### ISSUE TITLE
How to install it in Azure

### ISSUE THREAD

**Issue by miguelkennedy** [datamystic/share2predictbgl-bridge#1]
Hi,

I'm very interested in trying the Share to PredictBGL bridge. Looks very promising!

I can't find documentation on how to install it in Azure.

Can you help me?

Thanks!

**Comment by datamystic** [comment]
Hi - we don't use an Azure backend - we use ManageBGL.com. All you have to
do is install nodejs and then this script on your PC - it's a lot simpler
than setting up Azure.

Let me know if you need help with that.

Simon

**Comment by miguelkennedy** [comment]
Hi, Simon.

Thanks for the reply!

I installed nodejs in my remote linux (ubuntu) box but I'm getting errors when I try to run your script.

Here's what i did:
sudo apt-get update
sudo apt-get install nodejs
sudo apt-get install npm
npm install request
sudo ln -s /usr/bin/nodejs /usr/bin/node
git clone https://github.com/datamystic/share2predictbgl-bridge.git
cd share2predictbgl-bridge
set API_SECRET=[MyBGLPredictAPICode]
set DEXCOM_ACCOUNT_NAME=[MyUserName]
set DEXCOM_PASSWORD=[MyPassword]
node index.js

After I run the command "node index.js" I get the following errors:

/root/share2predictbgl-bridge/index.js:299
  if (readENV('API_SECRET').length < Defaults.MIN_PASSPHRASE_LENGTH) {
                           ^
TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/root/share2predictbgl-bridge/index.js:299:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

I must be doing something wrong :/

**Comment by datamystic** [comment]
Ah – on linux, use 

export

not

set

Let me know if I can help further.

Regards,

Simon Carter, DataMystic.com http://datamystic.com/   Skype:datamystic skype:datamystic?call   +61.3.9028.8594 (GMT+10 hours)  

PS. Know someone with diabetes? Tell them about PredictBGL Insulin Dose Calculator http://predictbgl.com/  PREDICTS future blood sugars, avoids hypos and coaches to better doses and better health 

TextPipe: PCMAG - "The ultimate text conversion and manipulation tool"

Detach Outlook Attachments and send huge files -  http://www.detachpipe.com/ DetachPipe.com

Download the latest Windows, Mac and iPhone software -  http://downloadpipe.com/ DownloadPipe.com

**Comment by miguelkennedy** [comment]
It worked :)))) Amazing!

Thanks for all the help, Simon. Much appreciated!

Wish you a great weekend!

**Comment by datamystic** [comment]
Thanks! Are you using the new Android version?

Let me know if I can help further.

Regards,

Simon Carter, DataMystic.com http://datamystic.com/   Skype:datamystic skype:datamystic?call   +61.3.9028.8594 (GMT+10 hours)  

PS. Know someone with diabetes? Tell them about PredictBGL Insulin Dose Calculator http://predictbgl.com/  PREDICTS future blood sugars, avoids hypos and coaches to better doses and better health 

TextPipe: PCMAG - "The ultimate text conversion and manipulation tool"

Detach Outlook Attachments and send huge files -  http://www.detachpipe.com/ DetachPipe.com

Download the latest Windows, Mac and iPhone software -  http://downloadpipe.com/ DownloadPipe.com

**Comment by miguelkennedy** [comment]
I'm using Dexcom G5 without Dexcom Receiver. As a receiver I use only my iPhone 6. In Europe you can get the sensors and transmitters without having to buy the Dexcom Receiver.

I use the PredictBGL iPhone app and I've also set up a Nightscout site.

Next step will be to get myself a Pebble or Apple Watch to have my BG in my wrist :)

**Comment by datamystic** [comment]
Cool. The next version of PredictBGL is much better at displaying Dexcom, but we need to resubmit it to AppStore. Looks like a Monday job L

Google Play went through no problems.

Let me know if I can help further.

Regards,

Simon Carter, DataMystic.com http://datamystic.com/   Skype:datamystic skype:datamystic?call   +61.3.9028.8594 (GMT+10 hours)  

PS. Know someone with diabetes? Tell them about PredictBGL Insulin Dose Calculator http://predictbgl.com/  PREDICTS future blood sugars, avoids hypos and coaches to better doses and better health 

TextPipe: PCMAG - "The ultimate text conversion and manipulation tool"

Detach Outlook Attachments and send huge files -  http://www.detachpipe.com/ DetachPipe.com

Download the latest Windows, Mac and iPhone software -  http://downloadpipe.com/ DownloadPipe.com
